### ISSUE TITLE
Extrastatus

### ISSUE THREAD

**Issue by fuschu** [bakkeby/patches#18]
I'm using flexipatch and wanted to separately align different text elements on the status bar, for example having text aligned to the left and right edges while also having one piece centered (see picture). Is there a way to create a third status element like with the extrastatus patch? I tried copying the code responsible for that patch but it just draws the same status in the middle.

![2021-01-10_1600x900](https://user-images.githubusercontent.com/76023075/104116719-43dd8b80-536f-11eb-8619-fb972e57a98f.png)

Great patch nonetheless, thank you for putting it together.

**Comment by bakkeby** [comment]
Hi @fuschu,

this is possible of course, it is just a little awkward to do.

The way the status works is that external applications set the X root name (via `xsetroot` or otherwise) and a bare dwm reads that and uses it as-is for the status text.

When it comes to the [extrabar](https://dwm.suckless.org/patches/extrabar/) and [dualstatus](https://dwm.suckless.org/patches/dualstatus/) patches they split said status text based on a delimiter, typically a semi-colon (`;`), leaving the status text up to the point of the delimiter to be the first status and everything after that becomes the second status.

In practice the text is copied out to a separate array and this happens within the `updatestatus` function.

```c
	} else {
		char *e = strchr(rawstext, statussep);
		if (e) {
			*e = '\0'; e++;
			strncpy(rawestext, e, sizeof(estext) - 1);
			copyvalidchars(estext, rawestext);
		} else
			estext[0] = '\0';
		copyvalidchars(stext, rawstext);
	}
```

To get a third status I think you'll want to do the same a second time, this time splitting `estext`.

It might look something like this (consider it pseudo code).

```c
	} else {
		char *e = strchr(rawstext, statussep);
		if (e) {
			*e = '\0'; e++;
			strncpy(rawestext, e, sizeof(estext) - 1);

			e = strchr(rawestext, statussep);
			if (e) {
				*e = '\0'; e++;
				strncpy(rawes2text, e, sizeof(estext2) - 1);
				copyvalidchars(estext2, rawes2text);
			} else
				estext2[0] = '\0';
			copyvalidchars(estext, rawestext);
		} else {
			estext[0] = '\0';
			estext2[0] = '\0';
		}
		copyvalidchars(stext, rawstext);
	}
```

The total length of all of these will obviously need to fit into the `rawstext` array, and if the first status is long then that will leave less space available to the remaining two statuses. Another obvious side effect is that all three statuses have to be updated together.

You will also need separate functions that work with this `estext2` (or whatever you want to call it) variable to print it on the status bar.

Slightly unrelated, but if you were to use the [IPC](https://dwm.suckless.org/patches/ipc/) patch then it is possible to set up functions similar to `updatestatus` to set the three statuses individually without having to search for a separator and copying text, etc.

**Comment by fuschu** [comment]
Hey,

thanks for the quick reply! Unfortunately

**Comment by fuschu** [comment]
Hey,
thanks for the quick re

**Comment by fuschu** [comment]
Hey,
thanks for the quick reply. I accidentally hit the wrong buttons and closed the issue.
Anyway, I tried implementing this code:
`

	} else {
		char *e = strchr(rawstext, statussep);
		if (e) {
			*e = '\0'; e++;
			strncpy(rawestext, e, sizeof(estext) - 1);
			e = strchr(rawestext, statussep);
			if (e) {
				*e = '\0'; e++;
				strncpy(rawestext2, e, sizeof(estext2) - 1);
				copyvalidchars(estext2, rawestext2);
			} else
				estext2[0] = '\0';
			copyvalidchars(estext, rawestext);
		} else {
			estext[0] = '\0';
			estext2[0] = '\0';
		}
		copyvalidchars(stext, rawstext);
	}

`
Unfortunately it just prints the second status text again in the new position, similar to what I had initially. I've tried changing things around etc. What exactly do you mean by 
> You will also need separate functions that work with this estext2 (or whatever you want to call it) variable to print it on the status bar.
I tried replicating everything done by the extrastatus patch again but with the new status and only found that block of code and creating `static char estext[1024];` and `static char rawestext[1024];`. Would I need to change anything in the `config.def.h`? I currently named the widthfunction and drawfunction for the new bar in barrules `width_status_es2` and `draw_status_es2` respectively and didn't give it any extra thought. Is there specific naming I need to take into account or does it not matter, as I assumed to due to the lack of errors?

I might try the IPC patch, although that looks too complicated for my novice capabilities.

Anyway, I appreciate the response to my more trivial issue.

**Comment by bakkeby** [comment]
> Unfortunately it just prints the second status text again in the new position, similar to what I had initially. I've tried changing things around etc. What exactly do you mean by
> > You will also need separate functions that work with this estext2 (or whatever you want to call it) variable to print it on the status bar.

That's assuming that you are using [barmodules](https://github.com/bakkeby/patches/wiki/barmodules) which comes with dwm-flexipatch. There is a separate [branch](https://github.com/bakkeby/dwm-flexipatch/tree/dwm-flexipatch-1.0) that has the original bar mechanism that comes with a bare dwm (mostly as a patch integration reference).

In `barrules` (in config.h) you probably have something like this right:
```c
{ 0,      0,     BAR_ALIGN_RIGHT,  width_status,        draw_status,        click_status,       "status" },
{ 0,      1,     BAR_ALIGN_CENTER, width_status_es,     draw_status_es,     click_status,       "status_es" },
```

If you look in [bar_status.c](https://github.com/bakkeby/dwm-flexipatch/blob/master/patch/bar_status.c) the main difference between e.g. `draw_status` and `draw_status_es` is that the former uses `stext` and the latter uses `estext`. If you create a third row also referring to `draw_status_es` then that is going to draw the second status one more time.

So you'll want separate functions that uses your third status `estext2` instead.

The above is referring to the basic status that comes with a bare dwm. If you are using [status2d](https://github.com/bakkeby/dwm-flexipatch/blob/master/patch/bar_status2d.c), the [powerline](https://github.com/bakkeby/dwm-flexipatch/blob/master/patch/bar_powerline_status.c) variant or otherwise then you'll have to add hooks for your third status in the respective module. This also applies to [statuscmd](https://github.com/bakkeby/dwm-flexipatch/blob/master/patch/bar_statuscmd.c) if you are also after button clicks.

**Comment by fuschu** [comment]
> If you look in bar_status.c

Holy crap, I feel like an idiot for never checking the patches folder... I just had to copy the width and draw functions.
Thank you so much!
