### ISSUE TITLE
dwm-systray-alpha 

### ISSUE THREAD

**Issue by kbc8090** [bakkeby/patches#2]
This patch seems to be broken now with the latest commits to dwm on the suckless git.  I tried to fix it by reading the few commits the past few weeks and editing your patch but I can't seem to get it to work.

Also I didnt know if you wanted to take a look at this guys systray patch to see if implementing it along with the alpha patch would be a better fit: 
https://www.reddit.com/r/suckless/comments/ezcemb/dwm_how_to_make_a_standalone_tray_app_always/

patch here: https://github.com/szatanjl/dwm/commit/f40d492ff9eedfcea6136c3d53155780b09b995a.patch

I tried for about 3 days to manually get a good systray and alpha patch going.  Frankly my only goal was to get OPAQUE borders on windows since the compositor (picom) likes to make these transparent too and the alpha patch prevents this by using ARGB values for the border.

**Comment by bakkeby** [comment]
You are right, that was broken, thanks for reporting. Took a bit of time to work out, but somehow I had ended up with 6.2 + 1 commit as my base for these patches. I have committed updates to these which are straight off 6.2.

I'd recommend just checking out (or branching off) 6.2 specifically, rather than master - you would not be missing anything as it's mostly non-functional changes (like changing a variable name in drawbar, that's where one of the conflicts come in). If need be I can arrange for an alpha-systray patch on top of the latest revision.

I did see szatanjl's comment about his systray, but looking over the diff I didn't spot exactly what he did differently and didn't have time to test it out.

If you want to just have a quick look at how it feels then I'd recommend just checking out my [dwm-flexipatch](https://github.com/bakkeby/dwm-flexipatch) build, enable both the alpha and systray patches, compile and you should be good to go.

**Comment by kbc8090** [comment]
Ok i grabbed dwm 6.2 and the patch does appear to be working however it seems the tag text and the status text (xsetroot) right side text is not opaque.  Also there's a problem with the spacing between systray icons and there being a dark or black patch that doens't look very good.  Lastly when using picom it's drawing double shadows under each systray item plus on the dwm bar so the shadow is extra thick there and is off-putting (this doesn't happen without the alpha patch).

I actually don't particularly need the alpha patch anymore as just yesterday about 30mins after I made the above post I found a very small and easy fix for creating opaque borders on my windows with a compositor running by the same guy that did that systray patch.

It's found here: https://github.com/szatanjl/dwm/commit/1529909466206016f2101457bbf37c67195714c8

In my opinion this should be in the dwm code by default seeing as automatic unconfigurable translucent borders when using a compositor shouldn't be something that happens.

I really love what you have done with the flexi-patch stuff, I did try out a few different things in dwm and it is working well.  I'm sure it has helped out quite a few people so far!

**Comment by bakkeby** [comment]
Nice! I'll be sure to incorporate that opaque borders fix in my flexipatch build. Thanks for the reference.

> it seems the tag text and the status text (xsetroot) right side text is not opaque
Yes this is intentional as far as I understand, ref. https://dwm.suckless.org/patches/alpha/
> _Allow dwm to have translucent bars, while keeping all the text on it opaque, just like the alpha-patch for st._

> Also there's a problem with the spacing between systray icons and there being a dark or black patch that doesn't look very good.
Hmm, do you have a screenshot perhaps? I don't have anything like this on my setup.

> Lastly when using picom it's drawing double shadows under each systray item plus on the dwm bar so the shadow is extra thick there and is off-putting (this doesn't happen without the alpha patch).
Yes I believe you are correct. I use compton myself (a predecessor to picom) and I had to add 
```
"class_g ?= 'dwm'"
```
to the shadow-exclude setting to get rid of the one from the bar. For the systray it draws a shadow per systray icon (I think), so rather than having to add each systray icon to the shadow-exclude I remember fiddling with other settings, most likely the shadow-offset to avoid shadows being created in the top right corner. There is also the no-dock-shadow setting, not sure if that does anything.

**Comment by kbc8090** [comment]
Yeah here is a screenshot of the black lines between icons

https://i.imgur.com/mgD044Z.png

**Comment by bakkeby** [comment]
Thanks, not entirely sure what would be causing that.

Do they also show if you kill picom?

Here's what mine looks like:
https://imgur.com/a/QBMBxkZ

**Comment by kbc8090** [comment]
Well each systray icon's background is black, so without the compositor the whole square icon area is black but with picom or xcompmgr on it's just not getting the space between the icons for some reason.  I tried with and without shadows on as well.

**Comment by bakkeby** [comment]
I didn't manage to replicate this issue until I started pulling the systray patch apart in relation to another project.

In the `updatesystray` function the background pixel is set for the new systray window:

```
wa.background_pixel = scheme[SchemeNorm][ColBg].pixel;
```

if we change that to the below then the systray window should be fully transparent.

```
wa.background_pixel = scheme[SchemeNorm][ColBg].pixel & 0x00ffffffU;
```

I'll add that to the patch.

**Comment by bakkeby** [comment]
Maybe I spoke too soon. I'll have a tinker.

**Comment by bakkeby** [comment]
```
+ dwm.c | 8 ++------
+ 1 file changed, 2 insertions(+), 6 deletions(-)
+
+diff --git a/dwm.c b/dwm.c
+index d155124..8cfbb1a 100644
+--- a/dwm.c
++++ b/dwm.c
+@@ -2254,7 +2254,7 @@ updatesystray(void)
+
+               wa.override_redirect = True;
+               wa.event_mask = ButtonPressMask|ExposureMask;
+-              wa.background_pixel = scheme[SchemeNorm][ColBg].pixel & 0x00ffffffU;
++              wa.background_pixel = 0;
+               wa.border_pixel = 0;
+               wa.colormap = cmap;
+               systray->win = XCreateWindow(dpy, root, x - xpad, m->by + ypad, w, bh, 0, depth,
+@@ -2283,8 +2283,7 @@ updatesystray(void)
+
+       drw_setscheme(drw, scheme[SchemeNorm]);
+       for (w = 0, i = systray->icons; i; i = i->next) {
+-              /* make sure the background color stays the same */
+-              wa.background_pixel = scheme[SchemeNorm][ColBg].pixel;
++              wa.background_pixel = 0;
+               XChangeWindowAttributes(dpy, i->win, CWBackPixel, &wa);
+               XMapRaised(dpy, i->win);
+               w += systrayspacing;
+@@ -2305,9 +2304,6 @@ updatesystray(void)
+       XConfigureWindow(dpy, systray->win, CWX|CWY|CWWidth|CWHeight|CWSibling|CWStackMode, &wc);
+       XMapWindow(dpy, systray->win);
+       XMapSubwindows(dpy, systray->win);
+-      /* redraw background */
+-      XSetForeground(dpy, drw->gc, scheme[SchemeNorm][ColBg].pixel);
+-      XFillRectangle(dpy, systray->win, drw->gc, 0, 0, w, bh);
+       XSync(dpy, False);
+ }
```
This seems to do the trick.

**Comment by bakkeby** [comment]
Going to consider this as closed.
