### ISSUE TITLE
dwm-vanitygaps-6.2.diff has references that shouldn't be there

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/patches#4]
dwm-vanitygaps-6.2.diff has pertag and cfacts references and other as well, I think you overlooked it when you updated the .diff file :)

**Comment by bakkeby** [comment]
There are no cfacts references in that diff file. For cfacts refer to dwm-cfacts-vanitygaps-6.2.diff.

There are facts references, needed to calculate the size of each client and the remainder following an even split.

The pertag references are intentional, they are hints should one want to integrate this on top of the pertag patch. The alternative would be to maintain 4 patches, which I really would want to avoid.
