### ISSUE TITLE
I know this is not related but, how do you solve the conflicting between patches?

### ISSUE THREAD

**Issue by daedmaet187** [bakkeby/patches#6]
I'm new to DWM, when I try to apply some patches and merge them on clean master branch I often get conflicting between those patches. So how do you get over this issue?

**Comment by bakkeby** [comment]
At the moment there are no functional changes on the clean master branch since 6.2, it's mostly cosmetic (style changes) and a case of a variable name being changed. There is also an unimportant change to config.mk that tends to break patches that updates that file (such as the alpha patch for example).

Typically patches that does anything with the status bar (and there are quite a few of those) will have conflicts with the latest code on master unless someone has put up a new dated / temporary patch.

So to start my recommendation would be to go with a strict 6.2 release and go from there - that way you'll have less conflicts with the patches that are out there. As-is there isn't any incentive for using a clean master over a 6.2 build simply because there is no new functional changes.

You can get a 6.2 build by cloning with the `-b 6.2` parameter
```
git clone -b 6.2 https://git.suckless.org/dwm
```
or from master you can check out 6.2
```
git checkout 6.2
```

As for answering your actual question; despite it being painfully time-consuming my recommendation is to always patch manually (by hand) rather than using `patch` or `git apply`.
The reason being that in order to get most out of dwm you kind of need to know a bit of how it works underneath the hood so that you can customise it to work just the way you want it to work. Once you get there then dwm is great, not because of what dwm is, but because you've made it your own.
You learn very little from running a command to apply a patch and now it works differently.

You _may_ also want to adopt a sane branching strategy for applying new patches and how you merge them in.

**Comment by daedmaet187** [comment]
Thanks for replying. 
Do you have any social media apps/accounts we can talk on? I have more questions if you don't mind.

**Comment by bakkeby** [comment]
I have a slack team / space for this purpose (if you happen to have slack):
https://github.com/bakkeby/dwm-vanitygaps/issues/6#issuecomment-577268552

**Comment by daedmaet187** [comment]
Yeah I do have. The link is no longer active.

**Comment by bakkeby** [comment]
Ah, wasn't aware that it would expire. Here's a new one:
https://join.slack.com/t/segfault-talk/shared_invite/zt-fmdoeghe-p_l0eepALcDQvlDO6iOjsw
