### ISSUE TITLE
How do we set custom color schemes for each components in barmodule?

### ISSUE THREAD

**Issue by mrsafalpiya** [bakkeby/patches#7]
As the title says, I want to change the color scheme for the status bar to make different foreground and background color.
I tried to do it myself but still no luck.
A solution like colorbar patch will be really great!
Help me!

**Comment by bakkeby** [comment]
The idea would be that each module handles colours on their own. You could add your own scheme and set that in the draw function for the module you'd want to change, e.g. in `draw_tags` you have this line in the for loop that controls colour:
```
drw_setscheme(drw, scheme[m->tagset[m->seltags] & 1 << i ? SchemeSel : SchemeNorm]);
```
You could then just swap out SchemeSel and SchemeNorm for your own schemes (SchemeTagsNorm and SchemeTagsSel for example).

I have changed the colour schemes used around a fair bit in my [dwm-flexipatch](https://github.com/bakkeby/dwm-flexipatch/) build and I'll likely port these into updated barmodules patches at some point. There are some significant changes so I'll have to have a look at how and what to include and if there are more changes going in before I do that.

**Comment by vide0hanz** [comment]
@mrsafalpiya FWIW I've been experimenting with this lately, turns out is pretty straightforward to create your own colorschemes. The colorbar patch code is doing exactly that, making additional schemes and inserting them into the code elsewhere. 

For example, in my build, I have this in config.h: 

```
static char *colors[][3] = {
       /*               fg           bg           border   */
       [SchemeNorm] = { normfgcolor, normbgcolor, normbordercolor },
       [SchemeAct]  = { actfgcolor,  actbgcolor,  normbordercolor },
       [SchemeSel]  = { selfgcolor,  selbgcolor,  selbordercolor  },
       [SchemeFoc]  = { normfgcolor, normbgcolor, selbordercolor  },
       [SchemeUrg]  = { selfgcolor,  selbgcolor,  urgentborder    },
       [SchemeHid]  = { hidfgcolor,  hidbgcolor,  selbordercolor  },
};
static const unsigned int baralpha = 0xd0;
static const unsigned int borderalpha = OPAQUE;
static const unsigned int hidalpha = 0xd0;
static const unsigned int alphas[][3]      = {
        /*               fg      bg        border     */
        [SchemeNorm] = { OPAQUE, baralpha, borderalpha },
        [SchemeAct]  = { OPAQUE, baralpha, borderalpha },
        [SchemeSel]  = { OPAQUE, baralpha, borderalpha },
        [SchemeFoc]  = { OPAQUE, OPAQUE,   borderalpha },
        [SchemeUrg]  = { OPAQUE, baralpha, borderalpha },
        [SchemeHid]  = { OPAQUE, hidalpha, borderalpha },
};
```
And in dwm.c, with the xrdb patch:

```
void
loadxrdb()
{
  Display *display;
  char * resm;
  XrmDatabase xrdb;
  char *type;
  XrmValue value;

  display = XOpenDisplay(NULL);

  if (display != NULL) {
    resm = XResourceManagerString(display);

    if (resm != NULL) {
      xrdb = XrmGetStringDatabase(resm);

      if (xrdb != NULL) {
        XRDB_LOAD_COLOR("dwm.color0", normbordercolor);
        XRDB_LOAD_COLOR("dwm.background", normbgcolor);
        XRDB_LOAD_COLOR("dwm.color7", normfgcolor);
        XRDB_LOAD_COLOR("dwm.color6", selbordercolor);
        XRDB_LOAD_COLOR("dwm.color5", selbgcolor);
        XRDB_LOAD_COLOR("dwm.color0", selfgcolor);
        XRDB_LOAD_COLOR("dwm.color7", hidbgcolor);
        XRDB_LOAD_COLOR("dwm.color0", hidfgcolor);
        XRDB_LOAD_COLOR("dwm.color0", actbgcolor);
        XRDB_LOAD_COLOR("dwm.color8", actfgcolor);
      }
    }
  }

  XCloseDisplay(display);
}
```
I can use the colors defined in ~/.Xresources in dwm and use them to create custom schemes this way. Of course you'll have to add whatever you decide to name them the `enum { SchemeNorm, SchemeSel, ... }` section as well. You probably notice I have the alpha patch as well, which as it turns out, you can set alpha values independently to specific schemes.

As @bakkeby already pointed out, you just merely change in the code which schemes you'd like to use for each particular module, for example in my bar_tags.c file:

```
if (m == selmon)
        drw_setscheme(drw, scheme[m->tagset[m->seltags] & 1 << i ? SchemeSel : SchemeNorm]);
else
        drw_setscheme(drw, scheme[m->tagset[m->seltags] & 1 << i ? SchemeAct : SchemeNorm]);
```

This is just telling dwm to use SchemeSel on an active monitor, else use SchemeAct if the monitor is not active.

Hope this helps.
